FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/openfox /usr/local/bin/openfox
COPY $TARGETPLATFORM/openfox-launcher /usr/local/bin/openfox-launcher

ENTRYPOINT ["openfox-launcher"]
CMD ["-console", "-public", "-no-browser"]
